dist: trusty
sudo: required
language:
  - cpp
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - g++-5
      - cmake
script:
  - export CC=gcc-5
  - export CXX=g++-5
  - mkdir build
  - cd build
  - cmake ..
  - make
  # - make test
