dist: trusty
sudo: required
language:
  - cpp
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - g++-5
      - cmake
script:
  # Export CC and CXX to tell cmake which compiler to use
  - export CC=gcc-5
  - gcc-5 --version
  - export CXX=g++-5
  - g++-5 --version
  - cmake --version
  # Build instructions.
  - mkdir build
  - cd build
  - cmake ..
  - make
  # - make test
